### PR TITLE
Interaction System

### LINKED ISSUE #3: Implement Interaction System

### PR DESCRIPTION
**Pull request by RicardoM17**
Closes #3

### CODE REVIEW

**Comment by RicardoM17** [comment]
@powercore2000 Can you have a look? It took me some time but I think I'm on the right track. I'm off for the night now so feel free to continue this and/or make any changes you see fit. Also feel free to merge it if it's done but I didn't get around to writing tests yet.

**Comment by powercore2000** [comment]
It looks like you've got the general idea down! I do have a couple of changes/notes I'd recommend:

-  Merging the functionality of InteractionSystem and ObjectSelectTrigger. That way one script handles checking for the trigger and will invoke an event if its triggered successfully. 
- Using unity's UnityEvent datatype instead of Action. That way it can be seen in the editor and assigned from there rather than from code every time.
- Decouple the Dice Control from the system. As long as it has a public method that represents the functionality you want to trigger when it is interacted with, it can be assigned via the editor to work when interacted with, as opposed to via code.
- Last thing is to namespace wrap the related systems. And add an assembly Definition file to the folder, so it can be unit tested later on.

Other than that, its solid! I'll try to leave this mechanic mostly for you to work on since its a good place to start with learning Unity specific interactions with code.

**Comment by RicardoM17** [comment]
@powercore2000 this should be good to go but feel free to review before I merge.

**Review by powercore2000 — APPROVED** [review]
Everything looks good to go! Eventualy we might want a different system then specifically OnMouseDown, but we'll worry about that at the input/controls statge

**Pull request merged**
